export const LOAD_ITEMS = "LOAD_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM_DETAILS = "UPDATE_ITEM_DETAILS";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
